let tablice = [3.4,5,2,4];
alert ("drugi element tablicy" + tablice[1]);
alert (`drugi element tablicy  ${tablice[1]}`);
alert (`dlugosc tablicy  ${tablice.length}`);
alert ("dlugosc tablicy" + tablice.length);
tablice.push(7);
alert("piaty element tablicey " + tablice[4]);
alert(`dlugosc tablicy ${ tablice.length}`);
tablice[1]=[7];
alert(tablice);
